
CREATE DATABASE kinderhaus;
USE kinderhaus;

CREATE TABLE funcionarios(
    FUN_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FUN_NOME VARCHAR(100) NOT NULL,
    FUN_CPF VARCHAR (100) NOT NULL,
    FUN_FUNCAO VARCHAR(100) NOT NULL,
    FUN_TEL VARCHAR(100) NOT NULL,
    FUN_ATIVO BOOLEAN NOT NULL DEFAULT TRUE

);

CREATE TABLE clientes(
    CLI_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_CPF VARCHAR (100) NOT NULL,
    CLI_TEL VARCHAR(100) NOT NULL,
    CLI_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CLI_DATANASC DATE NOT NULL,
    CLI_SENHA VARCHAR(255) NOT NULL,
    CLI_NOME_CRIANCA_1 VARCHAR(100) NOT NULL,
    CLI_IDADE_CRIANCA_1 INT NOT NULL,
    CLI_NOME_CRIANCA_2 VARCHAR(100),
    CLI_IDADE_CRIANCA_2 INT,
    CLI_NOME_CRIANCA_3 VARCHAR(100),
    CLI_IDADE_CRIANCA_3 INT,
    CLI_NOME_CRIANCA_4 VARCHAR(100),
    CLI_IDADE_CRIANCA_4 INT,
    CLI_NOME_CRIANCA_5 VARCHAR(100),
    CLI_IDADE_CRIANCA_5 INT,
    CLI_NOME_CRIANCA_6 VARCHAR(100),
    CLI_IDADE_CRIANCA_6 INT

);

-- CREATE TABLE DEPENDENTES?



CREATE TABLE usuarios(
    USU_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USU_LOGIN VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR (50) NOT NULL,
    FK_FUN_ID INT NOT NULL,
    USU_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
    
);

CREATE TABLE catalogo(
    CAT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CAT_NOME VARCHAR(100) NOT NULL,
    CAT_DESCRICAO VARCHAR (150) NULL,
    CAT_PRECO DECIMAL(10,2) NULL,
    CAT_TEMPO INT NULL,
    CAT_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CAT_IMAGE LONGBLOB
    
);

CREATE TABLE agenda(
    AG_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AG_HORA TIME NOT NULL,
    AG_DATA DATE NOT NULL,
    AG_STATUS CHAR(1) NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FK_CAT_ID INT NOT NULL,
    FK_FUN_ID INT NOT NULL
    
);

CREATE TABLE venda(
    VEN_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VEN_DATAHORA DATETIME NOT NULL,
    VEN_TOTAL DECIMAL (10,2) NOT NULL,
    FK_AG_ID INT NOT NULL
    
);

ALTER TABLE usuarios ADD CONSTRAINT USU_FUN FOREIGN KEY (FK_FUN_ID) REFERENCES funcionarios(FUN_ID);

ALTER TABLE agenda ADD CONSTRAINT AGE_CLI FOREIGN KEY (FK_CLI_ID) REFERENCES clientes(CLI_ID);

ALTER TABLE agenda ADD CONSTRAINT AGE_CAT FOREIGN KEY (FK_CAT_ID) REFERENCES catalogo(CAT_ID);

ALTER TABLE agenda ADD CONSTRAINT AGE_FUN FOREIGN KEY (FK_FUN_ID) REFERENCES funcionarios(FUN_ID);

ALTER TABLE venda ADD CONSTRAINT VEN_AGE FOREIGN KEY (FK_AG_ID) REFERENCES agenda(AG_ID);

 
INSERT INTO funcionarios (FUN_NOME, FUN_CPF, FUN_FUNCAO, FUN_TEL, FUN_ATIVO)
VALUES("Administrador", "11122233322", "Admin", "16981229988", 1);

INSERT INTO usuarios (USU_LOGIN, USU_SENHA, FK_FUN_ID, USU_ATIVO )
VALUES("administrador","admin123", 1, 1);


SELECT agenda.*, catalogo.*, cliente.CLI_NOME
FROM agenda
INNER JOIN catalogo ON FK_CAT_ID = CAT_ID
INNER JOIN cliente ON FK_CLI_ID = CLI_ID
ORDER BY AG_DATA DESC, AG_HORA ASC



ALTER TABLE agenda MODIFY FK_FUN_ID INT NULL;

ALTER TABLE clientes
ADD CLI_NOME_CONT_ALT_1 VARCHAR(100),
ADD CLI_TEL_CONT_ALT_1 VARCHAR(20),
ADD CLI_NOME_CONT_ALT_2 VARCHAR(100),
ADD CLI_TEL_CONT_ALT_2 VARCHAR(20);


ALTER TABLE venda
ADD VEN_STATUS ENUM('pendente','pago','cancelado') DEFAULT 'pendente',
ADD VEN_CLI_ID INT NOT NULL,
ADD CONSTRAINT VEN_CLI FOREIGN KEY (VEN_CLI_ID) REFERENCES clientes(CLI_ID);

ALTER TABLE catalogo MODIFY CAT_DESCRICAO VARCHAR(250);


-- ADD CONSTRAINT VEN_AGE FOREIGN KEY (FK_AG_ID) REFERENCES agenda(AG_ID);


-- colocar os inserts básicos no banco, cliente, serviço catalogo, agenda, funcionario e fazer uma venda